### ISSUE TITLE
Configuration sets incorrect value for APP_URL

### ISSUE THREAD

**Issue by schneider-felix** [wirduzen/shopdev#1]
The configuration currently sets an incorrect value for APP_URL. 
<img width="507" alt="image" src="https://github.com/user-attachments/assets/224b6f72-4d4a-4bd1-a01f-39dfa03cda26">
The port does not match the protocol. This breaks the admin watcher.

Furthermore the HOST and PORT variables are not set, which should also be set for the admin watcher.

For the admin watcher to work correctly, these variables should all be set to the non SSL version of the URL -> http://127.0.0.1

**Comment by zorrobert** [comment]
I changed the protocol to http. The HOST and PORT variables default to localhost and 80.
